export const types = {
    FILL_POSTS:    "FILL_POSTS",
    FILL_NEW_POST: "FILL_NEW_POST",
    CLEAR_POSTS:   "CLEAR_POSTS",

    FETCH_POSTS_ASYNC: "FETCH_POSTS_ASYNC",
    CREATE_POST_ASYNC: "CREATE_POST_ASYNC",
};
